---
# Manage Galaxy Eggs

- name: Fetch Galaxy eggs
  command: "{{ galaxy_venv_dir }}/bin/python {{ galaxy_server_dir }}/scripts/fetch_eggs.py -c {{ galaxy_config_file }} chdir={{ galaxy_server_dir }}"
  environment:
    GALAXY_EGGS_PATH: "{{ galaxy_eggs_path | default(galaxy_server_dir ~ '/eggs') }}"
  when: galaxy_fetch_eggs
  register: fetch_eggs_result
  changed_when: (fetch_eggs_result.rc == 0) and (fetch_eggs_result.stdout != "")
